### ISSUE TITLE
7 - City wide metrics design 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#56] opened 2017-03-07 00:39 UTC
1. Citywide Metrics  
2. Building type/citywide  
a. Filters for building type, neighborhood

**Comment by nicolettehayes** [comment] 2017-04-27 20:31
https://drive.google.com/file/d/0B5tBIGe_xercREk3WGxIMXY3SGs/view

**Comment by nicolettehayes** [comment] 2017-05-24 20:32
dupe of #66

**Closed as completed by nicolettehayes** 2017-05-24 20:32 UTC
Labels: design, phase 2, tables sprint
